- charts:
  - clusters:
    - master-test
    configuration:
      values:
        Component: demo-server
        CpuLimits: 200m
        CpuRequests: 25m
        Image:
          kuberlab.io/image:
            CandidateTag: '*'
            Name: kuberlab/demo-web-server
        MemoryLimits: 64Mi
        MemoryRequests: 64Mi
        Name: demo
        Replicas: 1
        ServerVersion: 1.2.0
    name: demo-web-server
    src: https://github.com/kuberlab/demo-web-server/Chart
    version: '*'
  name: kuberlab
- charts:
  - clusters:
    - master-test
    configuration: {}
    name: wordpress
    src: https://dev.kuberlab.io/kuberlab/wordpress
    version: '*'
  name: wordpress
- charts:
  - clusters:
    - test1
    configuration: {}
    name: test
    src: https://github.com/iljapoletaev/ku_test/chart
    version: 0.2.0
  name: sadad
- charts:
  - clusters:
    - master-test
    configuration:
      values:
        val: 1000
    name: test
    src: https://github.com/iljapoletaev/ku_test/chart
    version: 0.2.0
  - clusters:
    - master-test
    configuration:
      values:
        val: 1000
    name: test
    src: https://github.com/iljapoletaev/ku_test/chart
    version: 0.2.0
  - clusters:
    - test1
    configuration: {}
    name: test
    src: https://github.com/iljapoletaev/ku_test/chart
    version: 0.2.0
  name: sdfsdf
- charts:
  - clusters:
    - test1
    configuration: {}
    name: test
    src: https://github.com/iljapoletaev/ku_test/chart
    version: 0.2.0
  name: sdfsdfsdf
- charts:
  - clusters:
    - test1
    configuration: {}
    name: test
    src: https://github.com/iljapoletaev/ku_test/chart
    version: 0.2.0
  name: kjh
- charts:
  - clusters:
    - test1
    configuration: {}
    name: test
    src: https://github.com/iljapoletaev/ku_test/chart
    version: 0.2.0
  name: njhgvujg
